# The start symbol is START.

# These two rules are required; choose their weights carefully!
99 START -> S1
1 START -> S2

# This is a very, very, very simple grammar to get you started.

1 S1 -> PSub PVP .
1 S1 -> SSub SVP .

1 PSub -> PIPron
1 PSub -> PNP

1 SSub -> SIPron
1 SSub -> SNP

1 PNP -> Det PNbar
1 PNP -> PIPron
1 PNP -> PProper
1 PNP -> PPosPron PNbar

1 PNbar -> PNoun
1 PNbar -> PNbar PP
1 PNbar -> JJ PNbar

1 SNP -> Det SNbar
1 SNP -> SIPron
1 SNP -> SProper 
1 SNP -> SPosPron SNbar

1 SNbar -> SNoun
1 SNbar -> SNbar PP
1 SNbar -> JJ SNbar

1 PVP -> PVbar NP
10  PVbar -> PVerbT NP  
10  PVbar -> PVerbInt (PP)

1 SVP -> SVbar NP
10  SVbar -> SVerbT NP  
10  SVbar -> SVerbInt (PP)

10 NP -> SNP
10 NP -> PNP
  

1 PP -> Prep NP
